### ISSUE TITLE
Update to latest version of smbj for Java 17 support

### ISSUE THREAD

**Issue by neerajwadhwa-lcci** [swaechter/smbjwrapper#29]
**Bug description**

Hi @swaechter, there's a newer version of the smbj library that fixes some bugs caused by the update to Java like [this](https://stackoverflow.com/questions/77072622/getting-java-security-nosuchalgorithmexception-md4-messagedigest-not-available), is there any plans to update this library?

**Additional information**

* Version of smbj (0.11.5, from smbjwrapper pom) and smbjwrapper is 1.2.0

**Comment by swaechter** [comment]
Hi @neerajwadhwa-lcci

I just updated all dependencies and tried to upload to Maven Central. This failed because I have to migrate some stuff away from OSSRH. So I am blocked here.

But there is a workaround for Maven and Gradle to use smbjwrapper in version 1.2.0 with the latest smbj release. The idea is to exlude the smbj dependency from smbjwrapper and re-add the current smbj dependency.

## Maven

Change your pom.xml:

```xml
<dependencies>
	<dependency>
		<!-- Add the smbjwrapper dependency -->
		<groupId>ch.swaechter</groupId>
		<artifactId>smbjwrapper</artifactId>
		<version>1.2.0</version>
		<exclusions>
			<!-- Exclude the outdated compile dependency -->
			<exclusion>
				<groupId>com.hierynomus</groupId>
				<artifactId>smbj</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<!-- Re-add the current smbj dependency -->
	<dependency>
		<groupId>com.hierynomus</groupId>
		<artifactId>smbj</artifactId>
		<version>0.13.0</version>
	</dependency>
</dependencies>
```

You can verify the result with `mvn dependency:tree`:

```
[INFO] org.example:smbjtest-maven:jar:1.0-SNAPSHOT
[INFO] +- ch.swaechter:smbjwrapper:jar:1.2.0:compile
[INFO] \- com.hierynomus:smbj:jar:0.13.0:compile
[INFO]    +- org.slf4j:slf4j-api:jar:2.0.9:runtime
[INFO]    +- org.bouncycastle:bcprov-jdk18on:jar:1.75:runtime
[INFO]    +- net.engio:mbassador:jar:1.3.0:runtime
[INFO]    \- com.hierynomus:asn-one:jar:0.6.0:runtime
```

## Gradle

The same works for Gradle, see here: https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps

I guess it is also possible to keep the current smbjwrapper version and force the smbj version with the `!!` operator. This should look something like this (Untested):

```
implementation 'ch.swaechter:smbjwrapper:1.2.0'
implementation 'com.hierynomus:smbj:0.13.0!!'
```

Does this work for you?
